from .models import Ticker


def populate_tickers():
    ticker_data = [
        {"symbol": "AGUAS-A.SN", "company_name": "Aguas Andinas", "index": "IPSA"},
        {
            "symbol": "ANDINA-B.SN",
            "company_name": "Embotelladora Andina",
            "index": "IPSA",
        },
        {
            "symbol": "BCI.SN",
            "company_name": "Banco de Crédito e Inversiones",
            "index": "IPSA",
        },
        {
            "symbol": "BSANTANDER.SN",
            "company_name": "Banco Santander Chile",
            "index": "IPSA",
        },
        {"symbol": "CAP.SN", "company_name": "CAP", "index": "IPSA"},
        {
            "symbol": "CCU.SN",
            "company_name": "Compañía de Cervecerías Unidas",
            "index": "IPSA",
        },
        {
            "symbol": "CENCOSHOPP.SN",
            "company_name": "Cencosud Shopping S.A.",
            "index": "IPSA",
        },
        {"symbol": "CENCOSUD.SN", "company_name": "Cencosud S.A.", "index": "IPSA"},
        {"symbol": "CHILE.SN", "company_name": "Banco de Chile", "index": "IPSA"},
        {"symbol": "CMPC.SN", "company_name": "Empresas CMPC", "index": "IPSA"},
        {"symbol": "COLBUN.SN", "company_name": "Colbún", "index": "IPSA"},
        {
            "symbol": "CONCHATORO.SN",
            "company_name": "Viña Concha y Toro",
            "index": "IPSA",
        },
        {"symbol": "COPEC.SN", "company_name": "Copec", "index": "IPSA"},
        {"symbol": "ECL.SN", "company_name": "Engie", "index": "IPSA"},
        {"symbol": "ENELAM.SN", "company_name": "Enel Américas", "index": "IPSA"},
        {"symbol": "ENELCHILE.SN", "company_name": "Enel Chile", "index": "IPSA"},
        {"symbol": "ENTEL.SN", "company_name": "Entel Chile", "index": "IPSA"},
        {
            "symbol": "FALABELLA.SN",
            "company_name": "S.A.C.I. Falabella",
            "index": "IPSA",
        },
        {
            "symbol": "IAM.SN",
            "company_name": "Inversiones Aguas Metropolitanas",
            "index": "IPSA",
        },
        {"symbol": "ITAUCL.SN", "company_name": "Banco Itaú Chile", "index": "IPSA"},
        {
            "symbol": "LTM.SN",
            "company_name": "Latam Airlines Group S.A.",
            "index": "IPSA",
        },
        {"symbol": "MALLPLAZA.SN", "company_name": "Plaza S.A.", "index": "IPSA"},
        {
            "symbol": "ORO-BLANCO.SN",
            "company_name": "Sociedad de Inversiones Oro Blanco",
            "index": "IPSA",
        },
        {"symbol": "PARAUCO.SN", "company_name": "Parque Arauco", "index": "IPSA"},
        {"symbol": "QUINENCO.SN", "company_name": "Quiñenco S.A", "index": "IPSA"},
        {"symbol": "RIPLEY.SN", "company_name": "Ripley Corp. S.A.", "index": "IPSA"},
        {"symbol": "SMU.SN", "company_name": "SMU S.A.", "index": "IPSA"},
        {"symbol": "SONDA.SN", "company_name": "Sonda", "index": "IPSA"},
        {
            "symbol": "SQM-B.SN",
            "company_name": "Sociedad Química y Minera de Chile",
            "index": "IPSA",
        },
        {
            "symbol": "VAPORES.SN",
            "company_name": "Compañía Sudamericana de Vapores",
            "index": "IPSA",
        },
        {"symbol": "MMM", "company_name": "3M", "index": "S&P"},
        {"symbol": "AOS", "company_name": "A. O. Smith", "index": "S&P"},
        {"symbol": "ABT", "company_name": "Abbott", "index": "S&P"},
        {"symbol": "ABBV", "company_name": "AbbVie", "index": "S&P"},
        {"symbol": "ACN", "company_name": "Accenture", "index": "S&P"},
        {"symbol": "ADBE", "company_name": "Adobe Inc.", "index": "S&P"},
        {"symbol": "AMD", "company_name": "Advanced Micro Devices", "index": "S&P"},
        {"symbol": "AES", "company_name": "AES Corporation", "index": "S&P"},
        {"symbol": "AFL", "company_name": "Aflac", "index": "S&P"},
        {"symbol": "A", "company_name": "Agilent Technologies", "index": "S&P"},
        {"symbol": "APD", "company_name": "Air Products and Chemicals", "index": "S&P"},
        {"symbol": "ABNB", "company_name": "Airbnb", "index": "S&P"},
        {"symbol": "AKAM", "company_name": "Akamai", "index": "S&P"},
        {"symbol": "ALB", "company_name": "Albemarle Corporation", "index": "S&P"},
        {
            "symbol": "ARE",
            "company_name": "Alexandria Real Estate Equities",
            "index": "S&P",
        },
        {"symbol": "ALGN", "company_name": "Align Technology", "index": "S&P"},
        {"symbol": "ALLE", "company_name": "Allegion", "index": "S&P"},
        {"symbol": "LNT", "company_name": "Alliant Energy", "index": "S&P"},
        {"symbol": "ALL", "company_name": "Allstate", "index": "S&P"},
        {"symbol": "GOOGL", "company_name": "Alphabet Inc. (Class A)", "index": "S&P"},
        {"symbol": "GOOG", "company_name": "Alphabet Inc. (Class C)", "index": "S&P"},
        {"symbol": "MO", "company_name": "Altria", "index": "S&P"},
        {"symbol": "AMZN", "company_name": "Amazon", "index": "S&P"},
        {"symbol": "AMCR", "company_name": "Amcor", "index": "S&P"},
        {"symbol": "AEE", "company_name": "Ameren", "index": "S&P"},
        {"symbol": "AAL", "company_name": "American Airlines Group", "index": "S&P"},
        {"symbol": "AEP", "company_name": "American Electric Power", "index": "S&P"},
        {"symbol": "AXP", "company_name": "American Express", "index": "S&P"},
        {
            "symbol": "AIG",
            "company_name": "American International Group",
            "index": "S&P",
        },
        {"symbol": "AMT", "company_name": "American Tower", "index": "S&P"},
        {"symbol": "AWK", "company_name": "American Water Works", "index": "S&P"},
        {"symbol": "AMP", "company_name": "Ameriprise Financial", "index": "S&P"},
        {"symbol": "AME", "company_name": "Ametek", "index": "S&P"},
        {"symbol": "AMGN", "company_name": "Amgen", "index": "S&P"},
        {"symbol": "APH", "company_name": "Amphenol", "index": "S&P"},
        {"symbol": "ADI", "company_name": "Analog Devices", "index": "S&P"},
        {"symbol": "ANSS", "company_name": "Ansys", "index": "S&P"},
        {"symbol": "AON", "company_name": "Aon", "index": "S&P"},
        {"symbol": "APA", "company_name": "APA Corporation", "index": "S&P"},
        {"symbol": "AAPL", "company_name": "Apple Inc.", "index": "S&P"},
        {"symbol": "AMAT", "company_name": "Applied Materials", "index": "S&P"},
        {"symbol": "APTV", "company_name": "Aptiv", "index": "S&P"},
        {"symbol": "ACGL", "company_name": "Arch Capital Group", "index": "S&P"},
        {"symbol": "ADM", "company_name": "Archer-Daniels-Midland", "index": "S&P"},
        {"symbol": "ANET", "company_name": "Arista Networks", "index": "S&P"},
        {"symbol": "AJG", "company_name": "Arthur J. Gallagher & Co.", "index": "S&P"},
        {"symbol": "AIZ", "company_name": "Assurant", "index": "S&P"},
        {"symbol": "T", "company_name": "AT&T", "index": "S&P"},
        {"symbol": "ATO", "company_name": "Atmos Energy", "index": "S&P"},
        {"symbol": "ADSK", "company_name": "Autodesk", "index": "S&P"},
        {"symbol": "ADP", "company_name": "Automatic Data Processing", "index": "S&P"},
        {"symbol": "AZO", "company_name": "AutoZone", "index": "S&P"},
        {"symbol": "AVB", "company_name": "AvalonBay Communities", "index": "S&P"},
        {"symbol": "AVY", "company_name": "Avery Dennison", "index": "S&P"},
        {"symbol": "AXON", "company_name": "Axon Enterprise", "index": "S&P"},
        {"symbol": "BKR", "company_name": "Baker Hughes", "index": "S&P"},
        {"symbol": "BALL", "company_name": "Ball Corporation", "index": "S&P"},
        {"symbol": "BAC", "company_name": "Bank of America", "index": "S&P"},
        {"symbol": "BK", "company_name": "Bank of New York Mellon", "index": "S&P"},
        {"symbol": "BBWI", "company_name": "Bath & Body Works, Inc.", "index": "S&P"},
        {"symbol": "BAX", "company_name": "Baxter International", "index": "S&P"},
        {"symbol": "BDX", "company_name": "Becton Dickinson", "index": "S&P"},
        {"symbol": "BRK.B", "company_name": "Berkshire Hathaway", "index": "S&P"},
        {"symbol": "BBY", "company_name": "Best Buy", "index": "S&P"},
        {"symbol": "BIO", "company_name": "Bio-Rad", "index": "S&P"},
        {"symbol": "TECH", "company_name": "Bio-Techne", "index": "S&P"},
        {"symbol": "BIIB", "company_name": "Biogen", "index": "S&P"},
        {"symbol": "BLK", "company_name": "BlackRock", "index": "S&P"},
        {"symbol": "BX", "company_name": "Blackstone", "index": "S&P"},
        {"symbol": "BA", "company_name": "Boeing", "index": "S&P"},
        {"symbol": "BKNG", "company_name": "Booking Holdings", "index": "S&P"},
        {"symbol": "BWA", "company_name": "BorgWarner", "index": "S&P"},
        {"symbol": "BXP", "company_name": "Boston Properties", "index": "S&P"},
        {"symbol": "BSX", "company_name": "Boston Scientific", "index": "S&P"},
        {"symbol": "BMY", "company_name": "Bristol Myers Squibb", "index": "S&P"},
        {"symbol": "AVGO", "company_name": "Broadcom Inc.", "index": "S&P"},
        {
            "symbol": "BR",
            "company_name": "Broadridge Financial Solutions",
            "index": "S&P",
        },
        {"symbol": "BRO", "company_name": "Brown & Brown", "index": "S&P"},
        {"symbol": "BF.B", "company_name": "Brown–Forman", "index": "S&P"},
        {"symbol": "BLDR", "company_name": "Builders FirstSource", "index": "S&P"},
        {"symbol": "BG", "company_name": "Bunge Global SA", "index": "S&P"},
        {"symbol": "CDNS", "company_name": "Cadence Design Systems", "index": "S&P"},
        {"symbol": "CZR", "company_name": "Caesars Entertainment", "index": "S&P"},
        {"symbol": "CPT", "company_name": "Camden Property Trust", "index": "S&P"},
        {"symbol": "CPB", "company_name": "Campbell Soup Company", "index": "S&P"},
        {"symbol": "COF", "company_name": "Capital One", "index": "S&P"},
        {"symbol": "CAH", "company_name": "Cardinal Health", "index": "S&P"},
        {"symbol": "KMX", "company_name": "CarMax", "index": "S&P"},
        {"symbol": "CCL", "company_name": "Carnival", "index": "S&P"},
        {"symbol": "CARR", "company_name": "Carrier Global", "index": "S&P"},
        {"symbol": "CTLT", "company_name": "Catalent", "index": "S&P"},
        {"symbol": "CAT", "company_name": "Caterpillar Inc.", "index": "S&P"},
        {"symbol": "CBOE", "company_name": "Cboe Global Markets", "index": "S&P"},
        {"symbol": "CBRE", "company_name": "CBRE Group", "index": "S&P"},
        {"symbol": "CDW", "company_name": "CDW", "index": "S&P"},
        {"symbol": "CE", "company_name": "Celanese", "index": "S&P"},
        {"symbol": "COR", "company_name": "Cencora", "index": "S&P"},
        {"symbol": "CNC", "company_name": "Centene Corporation", "index": "S&P"},
        {"symbol": "CNP", "company_name": "CenterPoint Energy", "index": "S&P"},
        {"symbol": "CF", "company_name": "CF Industries", "index": "S&P"},
        {"symbol": "CHRW", "company_name": "CH Robinson", "index": "S&P"},
        {"symbol": "CRL", "company_name": "Charles River Laboratories", "index": "S&P"},
        {
            "symbol": "SCHW",
            "company_name": "Charles Schwab Corporation",
            "index": "S&P",
        },
        {"symbol": "CHTR", "company_name": "Charter Communications", "index": "S&P"},
        {"symbol": "CVX", "company_name": "Chevron Corporation", "index": "S&P"},
        {"symbol": "CMG", "company_name": "Chipotle Mexican Grill", "index": "S&P"},
        {"symbol": "CB", "company_name": "Chubb Limited", "index": "S&P"},
        {"symbol": "CHD", "company_name": "Church & Dwight", "index": "S&P"},
        {"symbol": "CI", "company_name": "Cigna", "index": "S&P"},
        {"symbol": "CINF", "company_name": "Cincinnati Financial", "index": "S&P"},
        {"symbol": "CTAS", "company_name": "Cintas", "index": "S&P"},
        {"symbol": "CSCO", "company_name": "Cisco", "index": "S&P"},
        {"symbol": "C", "company_name": "Citigroup", "index": "S&P"},
        {"symbol": "CFG", "company_name": "Citizens Financial Group", "index": "S&P"},
        {"symbol": "CLX", "company_name": "Clorox", "index": "S&P"},
        {"symbol": "CME", "company_name": "CME Group", "index": "S&P"},
        {"symbol": "CMS", "company_name": "CMS Energy", "index": "S&P"},
        {"symbol": "KO", "company_name": "Coca-Cola Company (The)", "index": "S&P"},
        {"symbol": "CTSH", "company_name": "Cognizant", "index": "S&P"},
        {"symbol": "CL", "company_name": "Colgate-Palmolive", "index": "S&P"},
        {"symbol": "CMCSA", "company_name": "Comcast", "index": "S&P"},
        {"symbol": "CMA", "company_name": "Comerica", "index": "S&P"},
        {"symbol": "CAG", "company_name": "Conagra Brands", "index": "S&P"},
        {"symbol": "COP", "company_name": "ConocoPhillips", "index": "S&P"},
        {"symbol": "ED", "company_name": "Consolidated Edison", "index": "S&P"},
        {"symbol": "STZ", "company_name": "Constellation Brands", "index": "S&P"},
        {"symbol": "CEG", "company_name": "Constellation Energy", "index": "S&P"},
        {"symbol": "COO", "company_name": "CooperCompanies", "index": "S&P"},
        {"symbol": "CPRT", "company_name": "Copart", "index": "S&P"},
        {"symbol": "GLW", "company_name": "Corning Inc.", "index": "S&P"},
        {"symbol": "CPAY", "company_name": "Corpay", "index": "S&P"},
        {"symbol": "CTVA", "company_name": "Corteva", "index": "S&P"},
        {"symbol": "CSGP", "company_name": "CoStar Group", "index": "S&P"},
        {"symbol": "COST", "company_name": "Costco", "index": "S&P"},
        {"symbol": "CTRA", "company_name": "Coterra", "index": "S&P"},
        {"symbol": "CCI", "company_name": "Crown Castle", "index": "S&P"},
        {"symbol": "CSX", "company_name": "CSX", "index": "S&P"},
        {"symbol": "CMI", "company_name": "Cummins", "index": "S&P"},
        {"symbol": "CVS", "company_name": "CVS Health", "index": "S&P"},
        {"symbol": "DHR", "company_name": "Danaher Corporation", "index": "S&P"},
        {"symbol": "DRI", "company_name": "Darden Restaurants", "index": "S&P"},
        {"symbol": "DVA", "company_name": "DaVita Inc.", "index": "S&P"},
        {"symbol": "DAY", "company_name": "Dayforce", "index": "S&P"},
        {"symbol": "DECK", "company_name": "Deckers Brands", "index": "S&P"},
        {"symbol": "DE", "company_name": "John Deere", "index": "S&P"},
        {"symbol": "DAL", "company_name": "Delta Air Lines", "index": "S&P"},
        {"symbol": "DVN", "company_name": "Devon Energy", "index": "S&P"},
        {"symbol": "DXCM", "company_name": "Dexcom", "index": "S&P"},
        {"symbol": "FANG", "company_name": "Diamondback Energy", "index": "S&P"},
        {"symbol": "DLR", "company_name": "Digital Realty", "index": "S&P"},
        {"symbol": "DFS", "company_name": "Discover Financial", "index": "S&P"},
        {"symbol": "DG", "company_name": "Dollar General", "index": "S&P"},
        {"symbol": "DLTR", "company_name": "Dollar Tree", "index": "S&P"},
        {"symbol": "D", "company_name": "Dominion Energy", "index": "S&P"},
        {"symbol": "DPZ", "company_name": "Domino's", "index": "S&P"},
        {"symbol": "DOV", "company_name": "Dover Corporation", "index": "S&P"},
        {"symbol": "DOW", "company_name": "Dow Inc.", "index": "S&P"},
        {"symbol": "DHI", "company_name": "DR Horton", "index": "S&P"},
        {"symbol": "DTE", "company_name": "DTE Energy", "index": "S&P"},
        {"symbol": "DUK", "company_name": "Duke Energy", "index": "S&P"},
        {"symbol": "DD", "company_name": "DuPont", "index": "S&P"},
        {"symbol": "EMN", "company_name": "Eastman Chemical Company", "index": "S&P"},
        {"symbol": "ETN", "company_name": "Eaton Corporation", "index": "S&P"},
        {"symbol": "EBAY", "company_name": "eBay", "index": "S&P"},
        {"symbol": "ECL", "company_name": "Ecolab", "index": "S&P"},
        {"symbol": "EIX", "company_name": "Edison International", "index": "S&P"},
        {"symbol": "EW", "company_name": "Edwards Lifesciences", "index": "S&P"},
        {"symbol": "EA", "company_name": "Electronic Arts", "index": "S&P"},
        {"symbol": "ELV", "company_name": "Elevance Health", "index": "S&P"},
        {"symbol": "LLY", "company_name": "Eli Lilly and Company", "index": "S&P"},
        {"symbol": "EMR", "company_name": "Emerson Electric", "index": "S&P"},
        {"symbol": "ENPH", "company_name": "Enphase", "index": "S&P"},
        {"symbol": "ETR", "company_name": "Entergy", "index": "S&P"},
        {"symbol": "EOG", "company_name": "EOG Resources", "index": "S&P"},
        {"symbol": "EPAM", "company_name": "EPAM Systems", "index": "S&P"},
        {"symbol": "EQT", "company_name": "EQT", "index": "S&P"},
        {"symbol": "EFX", "company_name": "Equifax", "index": "S&P"},
        {"symbol": "EQIX", "company_name": "Equinix", "index": "S&P"},
        {"symbol": "EQR", "company_name": "Equity Residential", "index": "S&P"},
        {"symbol": "ESS", "company_name": "Essex Property Trust", "index": "S&P"},
        {
            "symbol": "EL",
            "company_name": "Estée Lauder Companies (The)",
            "index": "S&P",
        },
        {"symbol": "ETSY", "company_name": "Etsy", "index": "S&P"},
        {"symbol": "EG", "company_name": "Everest Re", "index": "S&P"},
        {"symbol": "EVRG", "company_name": "Evergy", "index": "S&P"},
        {"symbol": "ES", "company_name": "Eversource", "index": "S&P"},
        {"symbol": "EXC", "company_name": "Exelon", "index": "S&P"},
        {"symbol": "EXPE", "company_name": "Expedia Group", "index": "S&P"},
        {"symbol": "EXPD", "company_name": "Expeditors International", "index": "S&P"},
        {"symbol": "EXR", "company_name": "Extra Space Storage", "index": "S&P"},
        {"symbol": "XOM", "company_name": "ExxonMobil", "index": "S&P"},
        {"symbol": "FFIV", "company_name": "F5, Inc.", "index": "S&P"},
        {"symbol": "FDS", "company_name": "FactSet", "index": "S&P"},
        {"symbol": "FICO", "company_name": "Fair Isaac", "index": "S&P"},
        {"symbol": "FAST", "company_name": "Fastenal", "index": "S&P"},
        {"symbol": "FRT", "company_name": "Federal Realty", "index": "S&P"},
        {"symbol": "FDX", "company_name": "FedEx", "index": "S&P"},
        {
            "symbol": "FIS",
            "company_name": "Fidelity National Information Services",
            "index": "S&P",
        },
        {"symbol": "FITB", "company_name": "Fifth Third Bank", "index": "S&P"},
        {"symbol": "FSLR", "company_name": "First Solar", "index": "S&P"},
        {"symbol": "FE", "company_name": "FirstEnergy", "index": "S&P"},
        {"symbol": "FI", "company_name": "Fiserv", "index": "S&P"},
        {"symbol": "FMC", "company_name": "FMC Corporation", "index": "S&P"},
        {"symbol": "F", "company_name": "Ford Motor Company", "index": "S&P"},
        {"symbol": "FTNT", "company_name": "Fortinet", "index": "S&P"},
        {"symbol": "FTV", "company_name": "Fortive", "index": "S&P"},
        {"symbol": "FOXA", "company_name": "Fox Corporation (Class A)", "index": "S&P"},
        {"symbol": "FOX", "company_name": "Fox Corporation (Class B)", "index": "S&P"},
        {"symbol": "BEN", "company_name": "Franklin Templeton", "index": "S&P"},
        {"symbol": "FCX", "company_name": "Freeport-McMoRan", "index": "S&P"},
        {"symbol": "GRMN", "company_name": "Garmin", "index": "S&P"},
        {"symbol": "IT", "company_name": "Gartner", "index": "S&P"},
        {"symbol": "GE", "company_name": "GE Aerospace", "index": "S&P"},
        {"symbol": "GEHC", "company_name": "GE HealthCare", "index": "S&P"},
        {"symbol": "GEV", "company_name": "GE Vernova", "index": "S&P"},
        {"symbol": "GEN", "company_name": "Gen Digital", "index": "S&P"},
        {"symbol": "GNRC", "company_name": "Generac", "index": "S&P"},
        {"symbol": "GD", "company_name": "General Dynamics", "index": "S&P"},
        {"symbol": "GIS", "company_name": "General Mills", "index": "S&P"},
        {"symbol": "GM", "company_name": "General Motors", "index": "S&P"},
        {"symbol": "GPC", "company_name": "Genuine Parts Company", "index": "S&P"},
        {"symbol": "GILD", "company_name": "Gilead Sciences", "index": "S&P"},
        {"symbol": "GPN", "company_name": "Global Payments", "index": "S&P"},
        {"symbol": "GL", "company_name": "Globe Life", "index": "S&P"},
        {"symbol": "GS", "company_name": "Goldman Sachs", "index": "S&P"},
        {"symbol": "HAL", "company_name": "Halliburton", "index": "S&P"},
        {"symbol": "HIG", "company_name": "Hartford (The)", "index": "S&P"},
        {"symbol": "HAS", "company_name": "Hasbro", "index": "S&P"},
        {"symbol": "HCA", "company_name": "HCA Healthcare", "index": "S&P"},
        {"symbol": "DOC", "company_name": "Healthpeak", "index": "S&P"},
        {"symbol": "HSIC", "company_name": "Henry Schein", "index": "S&P"},
        {"symbol": "HSY", "company_name": "Hershey's", "index": "S&P"},
        {"symbol": "HES", "company_name": "Hess Corporation", "index": "S&P"},
        {"symbol": "HPE", "company_name": "Hewlett Packard Enterprise", "index": "S&P"},
        {"symbol": "HLT", "company_name": "Hilton Worldwide", "index": "S&P"},
        {"symbol": "HOLX", "company_name": "Hologic", "index": "S&P"},
        {"symbol": "HD", "company_name": "Home Depot (The)", "index": "S&P"},
        {"symbol": "HON", "company_name": "Honeywell", "index": "S&P"},
        {"symbol": "HRL", "company_name": "Hormel Foods", "index": "S&P"},
        {"symbol": "HST", "company_name": "Host Hotels & Resorts", "index": "S&P"},
        {"symbol": "HWM", "company_name": "Howmet Aerospace", "index": "S&P"},
        {"symbol": "HPQ", "company_name": "HP Inc.", "index": "S&P"},
        {"symbol": "HUBB", "company_name": "Hubbell Incorporated", "index": "S&P"},
        {"symbol": "HUM", "company_name": "Humana", "index": "S&P"},
        {"symbol": "HBAN", "company_name": "Huntington Bancshares", "index": "S&P"},
        {
            "symbol": "HII",
            "company_name": "Huntington Ingalls Industries",
            "index": "S&P",
        },
        {"symbol": "IBM", "company_name": "IBM", "index": "S&P"},
        {"symbol": "IEX", "company_name": "IDEX Corporation", "index": "S&P"},
        {"symbol": "IDXX", "company_name": "Idexx Laboratories", "index": "S&P"},
        {"symbol": "ITW", "company_name": "Illinois Tool Works", "index": "S&P"},
        {"symbol": "ILMN", "company_name": "Illumina", "index": "S&P"},
        {"symbol": "INCY", "company_name": "Incyte", "index": "S&P"},
        {"symbol": "IR", "company_name": "Ingersoll Rand", "index": "S&P"},
        {"symbol": "PODD", "company_name": "Insulet", "index": "S&P"},
        {"symbol": "INTC", "company_name": "Intel", "index": "S&P"},
        {"symbol": "ICE", "company_name": "Intercontinental Exchange", "index": "S&P"},
        {
            "symbol": "IFF",
            "company_name": "International Flavors & Fragrances",
            "index": "S&P",
        },
        {"symbol": "IP", "company_name": "International Paper", "index": "S&P"},
        {
            "symbol": "IPG",
            "company_name": "Interpublic Group of Companies (The)",
            "index": "S&P",
        },
        {"symbol": "INTU", "company_name": "Intuit", "index": "S&P"},
        {"symbol": "ISRG", "company_name": "Intuitive Surgical", "index": "S&P"},
        {"symbol": "IVZ", "company_name": "Invesco", "index": "S&P"},
        {"symbol": "INVH", "company_name": "Invitation Homes", "index": "S&P"},
        {"symbol": "IQV", "company_name": "IQVIA", "index": "S&P"},
        {"symbol": "IRM", "company_name": "Iron Mountain", "index": "S&P"},
        {"symbol": "JBHT", "company_name": "J.B. Hunt", "index": "S&P"},
        {"symbol": "JBL", "company_name": "Jabil", "index": "S&P"},
        {"symbol": "JKHY", "company_name": "Jack Henry & Associates", "index": "S&P"},
        {"symbol": "J", "company_name": "Jacobs Solutions", "index": "S&P"},
        {"symbol": "JNJ", "company_name": "Johnson & Johnson", "index": "S&P"},
        {"symbol": "JCI", "company_name": "Johnson Controls", "index": "S&P"},
        {"symbol": "JPM", "company_name": "JPMorgan Chase", "index": "S&P"},
        {"symbol": "JNPR", "company_name": "Juniper Networks", "index": "S&P"},
        {"symbol": "K", "company_name": "Kellanova", "index": "S&P"},
        {"symbol": "KVUE", "company_name": "Kenvue", "index": "S&P"},
        {"symbol": "KDP", "company_name": "Keurig Dr Pepper", "index": "S&P"},
        {"symbol": "KEY", "company_name": "KeyCorp", "index": "S&P"},
        {"symbol": "KEYS", "company_name": "Keysight", "index": "S&P"},
        {"symbol": "KMB", "company_name": "Kimberly-Clark", "index": "S&P"},
        {"symbol": "KIM", "company_name": "Kimco Realty", "index": "S&P"},
        {"symbol": "KMI", "company_name": "Kinder Morgan", "index": "S&P"},
        {"symbol": "KLAC", "company_name": "KLA Corporation", "index": "S&P"},
        {"symbol": "KHC", "company_name": "Kraft Heinz", "index": "S&P"},
        {"symbol": "KR", "company_name": "Kroger", "index": "S&P"},
        {"symbol": "LHX", "company_name": "L3Harris", "index": "S&P"},
        {"symbol": "LH", "company_name": "LabCorp", "index": "S&P"},
        {"symbol": "LRCX", "company_name": "Lam Research", "index": "S&P"},
        {"symbol": "LW", "company_name": "Lamb Weston", "index": "S&P"},
        {"symbol": "LVS", "company_name": "Las Vegas Sands", "index": "S&P"},
        {"symbol": "LDOS", "company_name": "Leidos", "index": "S&P"},
        {"symbol": "LEN", "company_name": "Lennar", "index": "S&P"},
        {"symbol": "LIN", "company_name": "Linde plc", "index": "S&P"},
        {"symbol": "LYV", "company_name": "Live Nation Entertainment", "index": "S&P"},
        {"symbol": "LKQ", "company_name": "LKQ Corporation", "index": "S&P"},
        {"symbol": "LMT", "company_name": "Lockheed Martin", "index": "S&P"},
        {"symbol": "L", "company_name": "Loews Corporation", "index": "S&P"},
        {"symbol": "LOW", "company_name": "Lowe's", "index": "S&P"},
        {"symbol": "LULU", "company_name": "Lululemon Athletica", "index": "S&P"},
        {"symbol": "LYB", "company_name": "LyondellBasell", "index": "S&P"},
        {"symbol": "MTB", "company_name": "M&T Bank", "index": "S&P"},
        {"symbol": "MRO", "company_name": "Marathon Oil", "index": "S&P"},
        {"symbol": "MPC", "company_name": "Marathon Petroleum", "index": "S&P"},
        {"symbol": "MKTX", "company_name": "MarketAxess", "index": "S&P"},
        {"symbol": "MAR", "company_name": "Marriott International", "index": "S&P"},
        {"symbol": "MMC", "company_name": "Marsh McLennan", "index": "S&P"},
        {"symbol": "MLM", "company_name": "Martin Marietta Materials", "index": "S&P"},
        {"symbol": "MAS", "company_name": "Masco", "index": "S&P"},
        {"symbol": "MA", "company_name": "Mastercard", "index": "S&P"},
        {"symbol": "MTCH", "company_name": "Match Group", "index": "S&P"},
        {"symbol": "MKC", "company_name": "McCormick & Company", "index": "S&P"},
        {"symbol": "MCD", "company_name": "McDonald's", "index": "S&P"},
        {"symbol": "MCK", "company_name": "McKesson", "index": "S&P"},
        {"symbol": "MDT", "company_name": "Medtronic", "index": "S&P"},
        {"symbol": "MRK", "company_name": "Merck & Co.", "index": "S&P"},
        {"symbol": "META", "company_name": "Meta Platforms", "index": "S&P"},
        {"symbol": "MET", "company_name": "MetLife", "index": "S&P"},
        {"symbol": "MTD", "company_name": "Mettler Toledo", "index": "S&P"},
        {"symbol": "MGM", "company_name": "MGM Resorts", "index": "S&P"},
        {"symbol": "MCHP", "company_name": "Microchip Technology", "index": "S&P"},
        {"symbol": "MU", "company_name": "Micron Technology", "index": "S&P"},
        {"symbol": "MSFT", "company_name": "Microsoft", "index": "S&P"},
        {
            "symbol": "MAA",
            "company_name": "Mid-America Apartment Communities",
            "index": "S&P",
        },
        {"symbol": "MRNA", "company_name": "Moderna", "index": "S&P"},
        {"symbol": "MHK", "company_name": "Mohawk Industries", "index": "S&P"},
        {"symbol": "MOH", "company_name": "Molina Healthcare", "index": "S&P"},
        {
            "symbol": "TAP",
            "company_name": "Molson Coors Beverage Company",
            "index": "S&P",
        },
        {"symbol": "MDLZ", "company_name": "Mondelez International", "index": "S&P"},
        {"symbol": "MPWR", "company_name": "Monolithic Power Systems", "index": "S&P"},
        {"symbol": "MNST", "company_name": "Monster Beverage", "index": "S&P"},
        {"symbol": "MCO", "company_name": "Moody's Corporation", "index": "S&P"},
        {"symbol": "MS", "company_name": "Morgan Stanley", "index": "S&P"},
        {"symbol": "MOS", "company_name": "Mosaic Company (The)", "index": "S&P"},
        {"symbol": "MSI", "company_name": "Motorola Solutions", "index": "S&P"},
        {"symbol": "MSCI", "company_name": "MSCI", "index": "S&P"},
        {"symbol": "NDAQ", "company_name": "Nasdaq, Inc.", "index": "S&P"},
        {"symbol": "NTAP", "company_name": "NetApp", "index": "S&P"},
        {"symbol": "NFLX", "company_name": "Netflix", "index": "S&P"},
        {"symbol": "NEM", "company_name": "Newmont", "index": "S&P"},
        {"symbol": "NWSA", "company_name": "News Corp (Class A)", "index": "S&P"},
        {"symbol": "NWS", "company_name": "News Corp (Class B)", "index": "S&P"},
        {"symbol": "NEE", "company_name": "NextEra Energy", "index": "S&P"},
        {"symbol": "NKE", "company_name": "Nike, Inc.", "index": "S&P"},
        {"symbol": "NI", "company_name": "NiSource", "index": "S&P"},
        {"symbol": "NDSN", "company_name": "Nordson Corporation", "index": "S&P"},
        {"symbol": "NSC", "company_name": "Norfolk Southern Railway", "index": "S&P"},
        {"symbol": "NTRS", "company_name": "Northern Trust", "index": "S&P"},
        {"symbol": "NOC", "company_name": "Northrop Grumman", "index": "S&P"},
        {
            "symbol": "NCLH",
            "company_name": "Norwegian Cruise Line Holdings",
            "index": "S&P",
        },
        {"symbol": "NRG", "company_name": "NRG Energy", "index": "S&P"},
        {"symbol": "NUE", "company_name": "Nucor", "index": "S&P"},
        {"symbol": "NVDA", "company_name": "Nvidia", "index": "S&P"},
        {"symbol": "NVR", "company_name": "NVR, Inc.", "index": "S&P"},
        {"symbol": "NXPI", "company_name": "NXP Semiconductors", "index": "S&P"},
        {"symbol": "ORLY", "company_name": "O'Reilly Auto Parts", "index": "S&P"},
        {"symbol": "OXY", "company_name": "Occidental Petroleum", "index": "S&P"},
        {"symbol": "ODFL", "company_name": "Old Dominion", "index": "S&P"},
        {"symbol": "OMC", "company_name": "Omnicom Group", "index": "S&P"},
        {"symbol": "ON", "company_name": "ON Semiconductor", "index": "S&P"},
        {"symbol": "OKE", "company_name": "ONEOK", "index": "S&P"},
        {"symbol": "ORCL", "company_name": "Oracle Corporation", "index": "S&P"},
        {"symbol": "OTIS", "company_name": "Otis Worldwide", "index": "S&P"},
        {"symbol": "PCAR", "company_name": "Paccar", "index": "S&P"},
        {
            "symbol": "PKG",
            "company_name": "Packaging Corporation of America",
            "index": "S&P",
        },
        {"symbol": "PANW", "company_name": "Palo Alto Networks", "index": "S&P"},
        {"symbol": "PARA", "company_name": "Paramount Global", "index": "S&P"},
        {"symbol": "PH", "company_name": "Parker Hannifin", "index": "S&P"},
        {"symbol": "PAYX", "company_name": "Paychex", "index": "S&P"},
        {"symbol": "PAYC", "company_name": "Paycom", "index": "S&P"},
        {"symbol": "PYPL", "company_name": "PayPal", "index": "S&P"},
        {"symbol": "PNR", "company_name": "Pentair", "index": "S&P"},
        {"symbol": "PEP", "company_name": "PepsiCo", "index": "S&P"},
        {"symbol": "PFE", "company_name": "Pfizer", "index": "S&P"},
        {"symbol": "PCG", "company_name": "PG&E Corporation", "index": "S&P"},
        {"symbol": "PM", "company_name": "Philip Morris International", "index": "S&P"},
        {"symbol": "PSX", "company_name": "Phillips 66", "index": "S&P"},
        {"symbol": "PNW", "company_name": "Pinnacle West", "index": "S&P"},
        {"symbol": "PXD", "company_name": "Pioneer Natural Resources", "index": "S&P"},
        {"symbol": "PNC", "company_name": "PNC Financial Services", "index": "S&P"},
        {"symbol": "POOL", "company_name": "Pool Corporation", "index": "S&P"},
        {"symbol": "PPG", "company_name": "PPG Industries", "index": "S&P"},
        {"symbol": "PPL", "company_name": "PPL Corporation", "index": "S&P"},
        {"symbol": "PFG", "company_name": "Principal Financial Group", "index": "S&P"},
        {"symbol": "PG", "company_name": "Procter & Gamble", "index": "S&P"},
        {"symbol": "PGR", "company_name": "Progressive Corporation", "index": "S&P"},
        {"symbol": "PLD", "company_name": "Prologis", "index": "S&P"},
        {"symbol": "PRU", "company_name": "Prudential Financial", "index": "S&P"},
        {
            "symbol": "PEG",
            "company_name": "Public Service Enterprise Group",
            "index": "S&P",
        },
        {"symbol": "PTC", "company_name": "PTC", "index": "S&P"},
        {"symbol": "PSA", "company_name": "Public Storage", "index": "S&P"},
        {"symbol": "PHM", "company_name": "PulteGroup", "index": "S&P"},
        {"symbol": "QRVO", "company_name": "Qorvo", "index": "S&P"},
        {"symbol": "PWR", "company_name": "Quanta Services", "index": "S&P"},
        {"symbol": "QCOM", "company_name": "Qualcomm", "index": "S&P"},
        {"symbol": "DGX", "company_name": "Quest Diagnostics", "index": "S&P"},
        {"symbol": "RL", "company_name": "Ralph Lauren Corporation", "index": "S&P"},
        {"symbol": "RJF", "company_name": "Raymond James", "index": "S&P"},
        {"symbol": "RTX", "company_name": "RTX Corporation", "index": "S&P"},
        {"symbol": "O", "company_name": "Realty Income", "index": "S&P"},
        {"symbol": "REG", "company_name": "Regency Centers", "index": "S&P"},
        {"symbol": "REGN", "company_name": "Regeneron", "index": "S&P"},
        {
            "symbol": "RF",
            "company_name": "Regions Financial Corporation",
            "index": "S&P",
        },
        {"symbol": "RSG", "company_name": "Republic Services", "index": "S&P"},
        {"symbol": "RMD", "company_name": "ResMed", "index": "S&P"},
        {"symbol": "RVTY", "company_name": "Revvity", "index": "S&P"},
        {"symbol": "RHI", "company_name": "Robert Half", "index": "S&P"},
        {"symbol": "ROK", "company_name": "Rockwell Automation", "index": "S&P"},
        {"symbol": "ROL", "company_name": "Rollins, Inc.", "index": "S&P"},
        {"symbol": "ROP", "company_name": "Roper Technologies", "index": "S&P"},
        {"symbol": "ROST", "company_name": "Ross Stores", "index": "S&P"},
        {"symbol": "RCL", "company_name": "Royal Caribbean Group", "index": "S&P"},
        {"symbol": "SPGI", "company_name": "S&P Global", "index": "S&P"},
        {"symbol": "CRM", "company_name": "Salesforce", "index": "S&P"},
        {"symbol": "SBAC", "company_name": "SBA Communications", "index": "S&P"},
        {"symbol": "SLB", "company_name": "Schlumberger", "index": "S&P"},
        {"symbol": "STX", "company_name": "Seagate Technology", "index": "S&P"},
        {"symbol": "SRE", "company_name": "Sempra Energy", "index": "S&P"},
        {"symbol": "NOW", "company_name": "ServiceNow", "index": "S&P"},
        {"symbol": "SHW", "company_name": "Sherwin-Williams", "index": "S&P"},
        {"symbol": "SPG", "company_name": "Simon Property Group", "index": "S&P"},
        {"symbol": "SWKS", "company_name": "Skyworks Solutions", "index": "S&P"},
        {"symbol": "SJM", "company_name": "J.M. Smucker Company (The)", "index": "S&P"},
        {"symbol": "SNA", "company_name": "Snap-on", "index": "S&P"},
        {"symbol": "SOLV", "company_name": "Solventum", "index": "S&P"},
        {"symbol": "SO", "company_name": "Southern Company", "index": "S&P"},
        {"symbol": "LUV", "company_name": "Southwest Airlines", "index": "S&P"},
        {"symbol": "SWK", "company_name": "Stanley Black & Decker", "index": "S&P"},
        {"symbol": "SBUX", "company_name": "Starbucks", "index": "S&P"},
        {"symbol": "STT", "company_name": "State Street Corporation", "index": "S&P"},
        {"symbol": "STLD", "company_name": "Steel Dynamics", "index": "S&P"},
        {"symbol": "STE", "company_name": "Steris", "index": "S&P"},
        {"symbol": "SYK", "company_name": "Stryker Corporation", "index": "S&P"},
        {"symbol": "SMCI", "company_name": "Supermicro", "index": "S&P"},
        {"symbol": "SYF", "company_name": "Synchrony Financial", "index": "S&P"},
        {"symbol": "SNPS", "company_name": "Synopsys", "index": "S&P"},
        {"symbol": "SYY", "company_name": "Sysco", "index": "S&P"},
        {"symbol": "TMUS", "company_name": "T-Mobile US", "index": "S&P"},
        {"symbol": "TROW", "company_name": "T. Rowe Price", "index": "S&P"},
        {"symbol": "TTWO", "company_name": "Take-Two Interactive", "index": "S&P"},
        {"symbol": "TPR", "company_name": "Tapestry, Inc.", "index": "S&P"},
        {"symbol": "TRGP", "company_name": "Targa Resources", "index": "S&P"},
        {"symbol": "TGT", "company_name": "Target Corporation", "index": "S&P"},
        {"symbol": "TEL", "company_name": "TE Connectivity", "index": "S&P"},
        {"symbol": "TDY", "company_name": "Teledyne Technologies", "index": "S&P"},
        {"symbol": "TFX", "company_name": "Teleflex", "index": "S&P"},
        {"symbol": "TER", "company_name": "Teradyne", "index": "S&P"},
        {"symbol": "TSLA", "company_name": "Tesla, Inc.", "index": "S&P"},
        {"symbol": "TXN", "company_name": "Texas Instruments", "index": "S&P"},
        {"symbol": "TXT", "company_name": "Textron", "index": "S&P"},
        {"symbol": "TMO", "company_name": "Thermo Fisher Scientific", "index": "S&P"},
        {"symbol": "TJX", "company_name": "TJX Companies", "index": "S&P"},
        {"symbol": "TSCO", "company_name": "Tractor Supply", "index": "S&P"},
        {"symbol": "TT", "company_name": "Trane Technologies", "index": "S&P"},
        {"symbol": "TDG", "company_name": "TransDigm Group", "index": "S&P"},
        {"symbol": "TRV", "company_name": "Travelers Companies (The)", "index": "S&P"},
        {"symbol": "TRMB", "company_name": "Trimble Inc.", "index": "S&P"},
        {"symbol": "TFC", "company_name": "Truist", "index": "S&P"},
        {"symbol": "TYL", "company_name": "Tyler Technologies", "index": "S&P"},
        {"symbol": "TSN", "company_name": "Tyson Foods", "index": "S&P"},
        {"symbol": "USB", "company_name": "U.S. Bank", "index": "S&P"},
        {"symbol": "UBER", "company_name": "Uber", "index": "S&P"},
        {"symbol": "UDR", "company_name": "UDR, Inc.", "index": "S&P"},
        {"symbol": "ULTA", "company_name": "Ulta Beauty", "index": "S&P"},
        {"symbol": "UNP", "company_name": "Union Pacific Corporation", "index": "S&P"},
        {"symbol": "UAL", "company_name": "United Airlines Holdings", "index": "S&P"},
        {"symbol": "UPS", "company_name": "United Parcel Service", "index": "S&P"},
        {"symbol": "URI", "company_name": "United Rentals", "index": "S&P"},
        {"symbol": "UNH", "company_name": "UnitedHealth Group", "index": "S&P"},
        {"symbol": "UHS", "company_name": "Universal Health Services", "index": "S&P"},
        {"symbol": "VLO", "company_name": "Valero Energy", "index": "S&P"},
        {"symbol": "VTR", "company_name": "Ventas", "index": "S&P"},
        {"symbol": "VLTO", "company_name": "Veralto", "index": "S&P"},
        {"symbol": "VRSN", "company_name": "Verisign", "index": "S&P"},
        {"symbol": "VRSK", "company_name": "Verisk", "index": "S&P"},
        {"symbol": "VZ", "company_name": "Verizon", "index": "S&P"},
        {"symbol": "VRTX", "company_name": "Vertex Pharmaceuticals", "index": "S&P"},
        {"symbol": "VTRS", "company_name": "Viatris", "index": "S&P"},
        {"symbol": "VICI", "company_name": "Vici Properties", "index": "S&P"},
        {"symbol": "V", "company_name": "Visa Inc.", "index": "S&P"},
        {"symbol": "VMC", "company_name": "Vulcan Materials Company", "index": "S&P"},
        {"symbol": "WRB", "company_name": "Berkley", "index": "S&P"},
        {"symbol": "WAB", "company_name": "Wabtec", "index": "S&P"},
        {"symbol": "WBA", "company_name": "Walgreens Boots Alliance", "index": "S&P"},
        {"symbol": "WMT", "company_name": "Walmart", "index": "S&P"},
        {"symbol": "DIS", "company_name": "Walt Disney", "index": "S&P"},
        {"symbol": "WBD", "company_name": "Warner Bros. Discovery", "index": "S&P"},
        {"symbol": "WM", "company_name": "Waste Management", "index": "S&P"},
        {"symbol": "WAT", "company_name": "Waters Corporation", "index": "S&P"},
        {"symbol": "WEC", "company_name": "WEC Energy Group", "index": "S&P"},
        {"symbol": "WFC", "company_name": "Wells Fargo", "index": "S&P"},
        {"symbol": "WELL", "company_name": "Welltower", "index": "S&P"},
        {
            "symbol": "WST",
            "company_name": "West Pharmaceutical Services",
            "index": "S&P",
        },
        {"symbol": "WDC", "company_name": "Western Digital", "index": "S&P"},
        {"symbol": "WRK", "company_name": "WestRock", "index": "S&P"},
        {"symbol": "WY", "company_name": "Weyerhaeuser", "index": "S&P"},
        {"symbol": "WMB", "company_name": "Williams Companies", "index": "S&P"},
        {"symbol": "WTW", "company_name": "Willis Towers Watson", "index": "S&P"},
        {"symbol": "GWW", "company_name": "W. W. Grainger", "index": "S&P"},
        {"symbol": "WYNN", "company_name": "Wynn Resorts", "index": "S&P"},
        {"symbol": "XEL", "company_name": "Xcel Energy", "index": "S&P"},
        {"symbol": "XYL", "company_name": "Xylem Inc.", "index": "S&P"},
        {"symbol": "YUM", "company_name": "Yum! Brands", "index": "S&P"},
        {"symbol": "ZBRA", "company_name": "Zebra Technologies", "index": "S&P"},
        {"symbol": "ZBH", "company_name": "Zimmer Biomet", "index": "S&P"},
        {"symbol": "ZTS", "company_name": "Zoetis", "index": "S&P"},
    ]

    for data in ticker_data:
        Ticker.objects.create(**data)
